//
//  CatDetailViewController.swift
//  TheCatPragma
//
//  Created by CarlosDz on 9/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CatDetailViewController: UIViewController {

    @IBOutlet weak var catNameTitle: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    
    
    // MARK: - Public properties -
    var presenter: CatDetailPresenterInterface!

    // MARK: - Lifecycle -
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpView()
    }

    private func setUpView() {
        catNameTitle.text = presenter.catName
        descriptionLabel.text = presenter.catdescription
        
    }
}

// MARK: - Extensions -

extension CatDetailViewController: CatDetailViewInterface {
}
