//
//  CatListInterfaces.swift
//  TheCatPragma
//
//  Created by CarlosDz on 9/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum CatsResult {
    case ok([Cat])
    case error(String?)
}

protocol CatListWireframeInterface: WireframeInterface {
    func showDetail(cat: Cat)
}

protocol CatListViewInterface: ViewInterface {
    func reloadData()
}

protocol CatListPresenterInterface: PresenterInterface {
    var cats: [Cat] { get set }
    func getCats()
    func getCatModel(index: IndexPath) -> CatCellModel
    func showDetail(index: IndexPath)
}

protocol CatListInteractorInterface: InteractorInterface {
    func getCats(completion: @escaping ((CatsResult)->Void)) 
}
