//
//  CatListWireframe.swift
//  TheCatPragma
//
//  Created by CarlosDz on 9/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CatListWireframe: BaseWireframe<CatListViewController> {

    // MARK: - Module setup -

    init() {
        let moduleViewController = CatListViewController()
        super.init(viewController: moduleViewController)

        let interactor = CatListInteractor()
        let presenter = CatListPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CatListWireframe: CatListWireframeInterface {
}
