//
//  CatDetailPresenter.swift
//  TheCatPragma
//
//  Created by CarlosDz on 9/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CatDetailPresenter {

    // MARK: - Private properties -
    private unowned let view: CatDetailViewInterface
    private let interactor: CatDetailInteractorInterface
    private let wireframe: CatDetailWireframeInterface
    private let cat: Cat
    
    // MARK: - Lifecycle -
    init(
        view: CatDetailViewInterface,
        interactor: CatDetailInteractorInterface,
        wireframe: CatDetailWireframeInterface,
        cat: Cat
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.cat = cat
    }
}

// MARK: - Extensions -

extension CatDetailPresenter: CatDetailPresenterInterface {
    
    var catName: String { cat.breedName ?? "" }
    var catdescription: String { cat.description ?? "" }
}
