//
//  CatDetailInteractor.swift
//  TheCatPragma
//
//  Created by CarlosDz on 9/06/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CatDetailInteractor {
}

// MARK: - Extensions -

extension CatDetailInteractor: CatDetailInteractorInterface {
}
